services:
  # --- build db (SQL SERVER) ---
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=kXP4$'0}9E+)  #password!
    ports:
      - "1433:1433" #db port
    volumes:
      - sql_data_v2:/var/opt/mssql/data # prevention od cleaning data after restart

  # --- build backend (.NET) ---
  backend:
    build:
      context: ./backend
      dockerfile: CA_Presentation/Dockerfile
    container_name: backend_container
    ports:
      - "5118:8080"  # port from .env at FE
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  #dev mode
      # let docker find ip od db (top of file) by yourself
      - ConnectionStrings__DefaultConnection=Server=db;Database=CleanArchDB;User Id=sa;Password=kXP4$'0}9E+);TrustServerCertificate=True;
    depends_on:
      - db # backend have to wait for database

  #--- build frontend (TS React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5118/api  #connect via localhost (temp)
    volumes:
      - ./frontend:/app #live reload
      - /app/node_modules
    depends_on:
      - backend #frontend waiting for backend

volumes:
  sql_data_v2: